# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transliteration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'transliteration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15transliteration.proto\x12\x0ftransliteration\"&\n\x16TransliterationRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"6\n\x17TransliterationResponse\x12\x1b\n\x13transliterated_name\x18\x01 \x01(\t2|\n\x16TransliterationService\x12\x62\n\rTransliterate\x12\'.transliteration.TransliterationRequest\x1a(.transliteration.TransliterationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transliteration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSLITERATIONREQUEST']._serialized_start=42
  _globals['_TRANSLITERATIONREQUEST']._serialized_end=80
  _globals['_TRANSLITERATIONRESPONSE']._serialized_start=82
  _globals['_TRANSLITERATIONRESPONSE']._serialized_end=136
  _globals['_TRANSLITERATIONSERVICE']._serialized_start=138
  _globals['_TRANSLITERATIONSERVICE']._serialized_end=262
# @@protoc_insertion_point(module_scope)
