// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/entries": {
    params: {};
  };
  "/processing": {
    params: {};
  };
  "/databases": {
    params: {};
  };
  "/settings": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/entries" | "/processing" | "/databases" | "/settings";
  };
  "routes/layout.tsx": {
    id: "routes/layout";
    page: "/" | "/entries" | "/processing" | "/databases" | "/settings";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/entries.tsx": {
    id: "routes/entries";
    page: "/entries";
  };
  "routes/processing.tsx": {
    id: "routes/processing";
    page: "/processing";
  };
  "routes/databases.tsx": {
    id: "routes/databases";
    page: "/databases";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/layout": typeof import("./src/routes/layout.tsx");
  "routes/index": typeof import("./src/routes/index.tsx");
  "routes/entries": typeof import("./src/routes/entries.tsx");
  "routes/processing": typeof import("./src/routes/processing.tsx");
  "routes/databases": typeof import("./src/routes/databases.tsx");
  "routes/settings": typeof import("./src/routes/settings.tsx");
};